### ISSUE TITLE
Error thrown if creating duplicate key in object structure

### ISSUE THREAD

**Issue by Madd0g** [sgarciac/bombadil#14]
if I create a simple toml with a repeating object declaration, I get an error in `reader.errors`.

```toml
[obj]
subobj.id = 123
subobj.id = 456
```

`TypeError: Cannot read property 'type' of null`.

It would be nice to have a nicer error in this case.

Thanks! Great lib!
